tasks:

  - source: tasks/aggregate_data_vectors.py
    product:
      nb: '{{folder_output}}/notebooks/aggregate_data_vectors.ipynb'
      aggregated_data_vectors: '{{folder_output}}/aggregated_data_vectors/'
    params:
      folder_input: '{{folder_input}}'
      var: '{{var}}'
      year: '{{year}}'
      start_date: '{{start_date}}'
      end_date: '{{end_date}}'
      period: '{{period}}'
      agg_type: '{{agg_type}}'

  - source: tasks/aggregate_nodes.py
    product:
      nb: '{{folder_output}}/notebooks/aggregate_nodes.ipynb'
      aggregated_nodes: '{{folder_output}}/aggregated_nodes/'
    params:
      folder_input: '{{folder_input}}'
      year: '{{year}}'
      start_date: '{{start_date}}'
      end_date: '{{end_date}}'
      period: '{{period}}'
      agg_type: '{{agg_type}}'

  - source: tasks/calc_dist_matrix.py
    product:
      nb: '{{folder_output}}/notebooks/calc_dist_matrix.ipynb'
      calculated_dist_matrix: '{{folder_output}}/calculated_dist_matrix/'
    params:
      dist_matrix_type: '{{dist_matrix_type}}'

  - source: tasks/calc_nodes_means.py
    product:
      nb: '{{folder_output}}/notebooks/calc_nodes_means.ipynb'
      calculated_nodes_means: '{{folder_output}}/calculated_nodes_means/'

  - source: tasks/calc_vector_means.py
    product:
      nb: '{{folder_output}}/notebooks/calc_vector_means.ipynb'
      calculated_vector_means: '{{folder_output}}/calculated_vector_means/'

  - source: tasks/filter_data_nodes.py
    product:
      nb: '{{folder_output}}/notebooks/filter_data_nodes.ipynb'
      filtered_data_nodes: '{{folder_output}}/filtered_data_nodes/'

  - source: tasks/filter_data_with_datetime.py
    product:
      nb: '{{folder_output}}/notebooks/filter_data_with_datetime.ipynb'
      filtered_data_with_datetime: '{{folder_output}}/filtered_data_with_datetime/'
    params:
      var: '{{var}}'

  - source: tasks/plot_pm_by_regulations.py
    product:
      nb: '{{folder_output}}/notebooks/plots_by_regulations.ipynb'
      plots: '{{folder_output}}/plots_by_regulations/'
    params:
        folder_input: '{{folder_input}}'
        var: '{{var}}'
        year: '{{year}}'
        start_date: '{{start_date}}'
        end_date: '{{end_date}}'
        period: '{{period}}'
        agg_type: '{{agg_type}}'